name: week5sender
services:
  sender:
    build: .
    image: week5_05
    container_name: week5_sender01
    ports:
      - "8090:5000"
    environment:
      TARGET_BASE: http://host.docker.internal:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - sender_net
networks:
  sender_net:
    name: week5_net03
